version: '3'
services:
  couchbase:
    build: .
    ports:
      - 8091-8096:8091-8096
      - 11210-11211:11210-11211
      - 18091-18096:18091-18096
    environment:
      - COUCHBASE_HOST=localhost
      - COUCHBASE_USER=admin
      - COUCHBASE_PASSWORD=COUCHBASE_PASSWORD
    volumes:
      - ./couchbase:/opt/couchbase/var

      