version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USERNAME: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appDB
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
  web_server:
    build:
      context: ./
      dockerfile: Dockerfile 
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
  
    depends_on:
      - db
